# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\x12\x04\x63omm\"\x87\x01\n\x0bMapperInput\x12\x12\n\ninput_file\x18\x01 \x01(\t\x12\x14\n\x0cnum_reducers\x18\x02 \x01(\x05\x12\x14\n\x0cmapper_index\x18\x03 \x01(\x05\x12\x18\n\x10iteration_number\x18\x04 \x01(\x05\x12\x1e\n\tcentroids\x18\x05 \x03(\x0b\x32\x0b.comm.Point\"2\n\x0eMapperResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"H\n\x19GetPartitionedDataRequest\x12\x14\n\x0cmapper_index\x18\x01 \x01(\x05\x12\x15\n\rreducer_index\x18\x02 \x01(\x05\"\'\n\tDataEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06values\x18\x02 \x03(\x02\"W\n\x11PartitionResponse\x12 \n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0f.comm.DataEntry\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"T\n\x0cReducerInput\x12\x18\n\x10iteration_number\x18\x01 \x01(\x05\x12\x15\n\rreducer_index\x18\x02 \x01(\x05\x12\x13\n\x0bnum_mappers\x18\x03 \x01(\x05\"3\n\x0fReducerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x95\x01\n\rMapperService\x12\x34\n\tSendInput\x12\x11.comm.MapperInput\x1a\x14.comm.MapperResponse\x12N\n\x12GetPartitionedData\x12\x1f.comm.GetPartitionedDataRequest\x1a\x17.comm.PartitionResponse2L\n\x0eReducerService\x12:\n\rProcessReduce\x12\x12.comm.ReducerInput\x1a\x15.comm.ReducerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPPERINPUT']._serialized_start=21
  _globals['_MAPPERINPUT']._serialized_end=156
  _globals['_MAPPERRESPONSE']._serialized_start=158
  _globals['_MAPPERRESPONSE']._serialized_end=208
  _globals['_GETPARTITIONEDDATAREQUEST']._serialized_start=210
  _globals['_GETPARTITIONEDDATAREQUEST']._serialized_end=282
  _globals['_DATAENTRY']._serialized_start=284
  _globals['_DATAENTRY']._serialized_end=323
  _globals['_PARTITIONRESPONSE']._serialized_start=325
  _globals['_PARTITIONRESPONSE']._serialized_end=412
  _globals['_POINT']._serialized_start=414
  _globals['_POINT']._serialized_end=443
  _globals['_REDUCERINPUT']._serialized_start=445
  _globals['_REDUCERINPUT']._serialized_end=529
  _globals['_REDUCERRESPONSE']._serialized_start=531
  _globals['_REDUCERRESPONSE']._serialized_end=582
  _globals['_MAPPERSERVICE']._serialized_start=585
  _globals['_MAPPERSERVICE']._serialized_end=734
  _globals['_REDUCERSERVICE']._serialized_start=736
  _globals['_REDUCERSERVICE']._serialized_end=812
# @@protoc_insertion_point(module_scope)
